name: moth
description: moth

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dio: ^5.1.1
  collection: ^1.17.0
  bloc_concurrency: ^0.2.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.4
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  injectable: ^2.1.1
  intl: ^0.18.0
  modal_bottom_sheet: ^2.1.2
  permission_handler: ^10.2.0
  provider: ^6.0.5
  rive: ^0.10.3
  rxdart: ^0.27.7
  share_plus: ^6.3.1
  shared_preferences: ^2.1.0
  sliver_tools: ^0.2.9
  webview_flutter: ^4.0.7
  uuid: ^3.0.7
  url_launcher: ^6.1.10
  uni_links: ^0.5.1
  logger: ^1.3.0
  firebase_auth: ^4.4.0
  auto_route: ^6.0.5
  firebase_core: ^2.9.0
  firebase_app_check: ^0.1.4+2
  cloud_firestore: ^4.5.0
  cloud_functions: ^4.1.0
  firebase_messaging: ^14.4.0
  firebase_database: ^10.1.0
  pin_code_fields: ^7.4.0
  flutter_switch: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.5
  theme_tailor: ^1.1.2
  dart_code_metrics: ^5.7.0
  auto_route_generator: ^6.0.3

flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/riv/
    - assets/icons/

