// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFbklY-YFb_oyhdp57C7AS8hsO1yI5YhQ',
    appId: '1:95216773866:web:a67d2b46728c5e02000593',
    messagingSenderId: '95216773866',
    projectId: 'moth-27a1f',
    authDomain: 'moth-27a1f.firebaseapp.com',
    storageBucket: 'moth-27a1f.appspot.com',
    measurementId: 'G-LDYY4RC750',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT7l9C-S0xYXcB8UnEVN_hZXiHMh4h1Es',
    appId: '1:95216773866:android:5e77ecd8d56d075d000593',
    messagingSenderId: '95216773866',
    projectId: 'moth-27a1f',
    storageBucket: 'moth-27a1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwEnbObTdn9R4PqIVQbFf7VLd6SBqZxOM',
    appId: '1:95216773866:ios:b119900fd153c4e1000593',
    messagingSenderId: '95216773866',
    projectId: 'moth-27a1f',
    storageBucket: 'moth-27a1f.appspot.com',
    iosClientId: '95216773866-714pip2n0p15ji2vj9u6pvg5dil9ne5f.apps.googleusercontent.com',
    iosBundleId: 'com.eclipsedevelop.moth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwEnbObTdn9R4PqIVQbFf7VLd6SBqZxOM',
    appId: '1:95216773866:ios:b119900fd153c4e1000593',
    messagingSenderId: '95216773866',
    projectId: 'moth-27a1f',
    storageBucket: 'moth-27a1f.appspot.com',
    iosClientId: '95216773866-714pip2n0p15ji2vj9u6pvg5dil9ne5f.apps.googleusercontent.com',
    iosBundleId: 'com.eclipsedevelop.moth',
  );
}
